//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace univercity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teacher_presonal_information
    {
        public string code_national_teacher { get; set; }
        public string password { get; set; }
        public string name_teacher { get; set; }
        public string family_teacher { get; set; }
        public string name_father { get; set; }
        public Nullable<bool> code_sex { get; set; }
        public string number_birth_certificate { get; set; }
        public Nullable<int> code_state { get; set; }
        public Nullable<int> code_city { get; set; }
        public Nullable<int> code_city_place_issue { get; set; }
        public Nullable<System.DateTime> date_birth { get; set; }
        public Nullable<int> code_religion_din { get; set; }
        public Nullable<int> code_religion_mazhab { get; set; }
        public Nullable<bool> code_national { get; set; }
        public string name_country { get; set; }
        public string phone_number { get; set; }
        public string phone_home { get; set; }
        public string address_home { get; set; }
        public string email { get; set; }
        public byte[] picture { get; set; }
        public Nullable<int> code_status_marrid { get; set; }
        public Nullable<int> code_status_employment { get; set; }
        public Nullable<int> code_status_occupation { get; set; }
        public Nullable<int> code_occupation { get; set; }
        public Nullable<int> code_type_cooperation { get; set; }
        public string phone_work { get; set; }
        public string address_work { get; set; }
        public string phone_necessary { get; set; }
        public Nullable<int> code_status_duty_system { get; set; }
        public Nullable<System.DateTime> date_end_duty_system { get; set; }
        public string code_personnel { get; set; }
        public string faivorite { get; set; }
        public string name_user { get; set; }
        public Nullable<System.DateTime> date_insert_information { get; set; }
        public Nullable<int> code_group_lesson { get; set; }
        public Nullable<bool> code_status_account { get; set; }
    }
}
